services:
  # Backend API service
  - type: web
    name: cbstandup-api
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm run start:prod
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: cbstandup-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cbstandup-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: cbstandup-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cbstandup-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: cbstandup-db
          property: database
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false

  # Frontend service
  - type: static
    name: cbstandup-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cbstandup-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: cbstandup-db
    databaseName: cbstandup
    plan: free
    user: cbstandup 