services:
  # Backend API service
  - type: web
    name: cbstandup-api
    env: docker
    plan: free
    dockerfilePath: ./server/Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: cbstandup-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cbstandup-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: cbstandup-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cbstandup-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: cbstandup-db
          property: database
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  # Frontend service
  - type: web
    name: cbstandup-web
    env: docker
    plan: free
    dockerfilePath: ./src/Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://cbstandup-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: cbstandup-db
    databaseName: cbstandup
    user: postgres
    plan: free 