services:
  - type: web
    name: cbstandup
    env: docker
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: cbstandup-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: cbstandup-db
    databaseName: cbstandup
    plan: free
    user: cbstandup 